-- 1)Total number of records in each table
SELECT COUNT(*) AS total_enrollments FROM enrollments;
SELECT COUNT(*) AS total_courses FROM courses;

-- Check for duplicate enrollments (same student, same course, same date)
SELECT student_id, course_id, enrollment_date, COUNT(*) AS dup_count
FROM enrollments
GROUP BY student_id, course_id, enrollment_date
HAVING COUNT(*) > 1;

-- Check for NULL values in critical columns
SELECT 
    SUM(CASE WHEN course_id IS NULL THEN 1 ELSE 0 END) AS null_course_id,
    SUM(CASE WHEN enrollment_date IS NULL THEN 1 ELSE 0 END) AS null_enrollment_date,
    SUM(CASE WHEN status IS NULL THEN 1 ELSE 0 END) AS null_status
FROM enrollments;

-- Date range of the dataset
SELECT 
    MIN(enrollment_date) AS first_enrollment,
    MAX(enrollment_date) AS last_enrollment
FROM enrollments;


-- 2) Enrollment count by course category
SELECT 
    c.category,
    COUNT(e.enrollment_id) AS total_enrollments
FROM enrollments e
JOIN courses c ON e.course_id = c.course_id
GROUP BY c.category
ORDER BY total_enrollments DESC;

-- Distribution of course prices

WITH price_stats AS (
    SELECT 
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY price_usd) 
            OVER () AS median_price
    FROM courses
)
SELECT 
    MIN(price_usd) AS min_price,
    MAX(price_usd) AS max_price,
    ROUND(AVG(price_usd), 2) AS avg_price,
    MAX(median_price) AS median_price  -- use MAX since it's the same for all rows
FROM courses
CROSS JOIN price_stats;

-- Most popular courses (by enrollments)


SELECT TOP 10
    c.course_name,
    COUNT(e.enrollment_id) AS total_enrollments
FROM enrollments e
JOIN courses c ON e.course_id = c.course_id
GROUP BY c.course_name
ORDER BY total_enrollments DESC;


-- 3)Relationships between variables.
-- Completion rates per course
SELECT 
    c.course_name,
    COUNT(e.enrollment_id) AS total_enrollments,
    SUM(CASE WHEN e.status = 'Completed' THEN 1 ELSE 0 END) AS completed_count,
    ROUND(
        (CAST(SUM(CASE WHEN e.status = 'Completed' THEN 1 ELSE 0 END) AS FLOAT) / 
         COUNT(e.enrollment_id)) * 100, 2
    ) AS completion_rate_pct
FROM enrollments e
JOIN courses c ON e.course_id = c.course_id
GROUP BY c.course_name
ORDER BY completion_rate_pct DESC;

-- Completion rate by category
SELECT 
    c.category,
    COUNT(e.enrollment_id) AS total_enrollments,
    ROUND(
        (CAST(SUM(CASE WHEN e.status = 'Completed' THEN 1 ELSE 0 END) AS FLOAT) /
         COUNT(e.enrollment_id)) * 100, 2
    ) AS completion_rate_pct
FROM enrollments e
JOIN courses c ON e.course_id = c.course_id
GROUP BY c.category
ORDER BY completion_rate_pct DESC;

-- Does price affect completion rate?
SELECT 
    ROUND(c.price_usd,0) AS price_bucket,
    COUNT(e.enrollment_id) AS total_enrollments,
    ROUND(
        (CAST(SUM(CASE WHEN e.status = 'Completed' THEN 1 ELSE 0 END) AS FLOAT) / 
         COUNT(e.enrollment_id)) * 100, 2
    ) AS completion_rate_pct
FROM enrollments e
JOIN courses c ON e.course_id = c.course_id
GROUP BY ROUND(c.price_usd,0)
ORDER BY price_bucket;



-- 4)Monthly enrollment trends
SELECT 
    FORMAT(enrollment_date, 'yyyy-MM') AS enrollment_month,
    COUNT(enrollment_id) AS total_enrollments
FROM enrollments
GROUP BY FORMAT(enrollment_date, 'yyyy-MM')
ORDER BY enrollment_month;


-- 5)Revenue generated by course
SELECT 
    c.course_name,
    COUNT(e.enrollment_id) AS total_enrollments,
    c.price_usd,
    ROUND(COUNT(e.enrollment_id) * c.price_usd, 2) AS total_revenue_usd
FROM enrollments e
JOIN courses c ON e.course_id = c.course_id
GROUP BY c.course_name, c.price_usd
ORDER BY total_revenue_usd DESC;